// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfjhHUXIDIOguMJHBKE2N38_mW6jsYAlY',
    appId: '1:720535218130:web:f7b328fb30d1e2e2f7ca0b',
    messagingSenderId: '720535218130',
    projectId: 'chat-app-6f534',
    authDomain: 'chat-app-6f534.firebaseapp.com',
    storageBucket: 'chat-app-6f534.appspot.com',
    measurementId: 'G-HWWWFXMRD0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9Wry4vF1kMEgPzdxBhjdyat-iwsk8UyY',
    appId: '1:720535218130:android:f0d17ef2cdcda77cf7ca0b',
    messagingSenderId: '720535218130',
    projectId: 'chat-app-6f534',
    storageBucket: 'chat-app-6f534.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBty6ufpNqve3tJbaOW-9mbH2qkHYp5Hs',
    appId: '1:720535218130:ios:99714d60be28ebb3f7ca0b',
    messagingSenderId: '720535218130',
    projectId: 'chat-app-6f534',
    storageBucket: 'chat-app-6f534.appspot.com',
    iosBundleId: 'com.example.scholarChat',
  );
}
